Repository Usic-Room/fe, pull requests merged in 2024-11, with the labels that each got.

#34 Refactor: 기존 코드를 모바일 반응형으로 변경
  package-lock.json
  public/images/home.svg
  public/images/plus-lg.svg
  public/images/search.svg
  public/mockServiceWorker.js
  src/app/(main)/home/layout.tsx
  src/app/(main)/home/page.tsx
  src/app/(main)/home/search/page.tsx
  src/components/home/navRegisterButtons.tsx
  src/components/home/navigation.tsx
  src/components/home/searchBar.tsx
Labels: refactor

#36 Style: register page mobile view implement
  src/components/(auth)/register/clientComponents.tsx
  src/components/(auth)/register/serverComponents.tsx
Labels: style

#38 Fix: attach searchBar with logo in main page
  src/components/home/navigation.tsx
Labels: fix

#39 Refactor: Components 위치 및 home components 분리
  package-lock.json
  package.json
  src/app/(auth)/login/page.tsx
  src/app/(auth)/login/reset-password/email/page.tsx
  src/app/(auth)/login/reset-password/page.tsx
  src/app/(auth)/login/reset-password/success/page.tsx
  src/app/(auth)/oauth/page.tsx
  src/app/(auth)/register/page.tsx
  src/app/(auth)/register/password/page.tsx
  src/app/(auth)/register/terms/page.tsx
  src/app/(auth)/register/username/page.tsx
  src/app/(auth)/register/verification/page.tsx
  src/app/(main)/home/layout.tsx
  src/app/(main)/home/page.tsx
  src/app/(main)/home/search/page.tsx
  src/app/_components/(auth)/login/clientComponents.tsx
  src/app/_components/(auth)/login/reset-password/clientComponents.tsx
  src/app/_components/(auth)/login/reset-password/email/clientComponents.tsx
  src/app/_components/(auth)/login/reset-password/email/serverComponents.tsx
  src/app/_components/(auth)/login/reset-password/serverComponents.tsx
  src/app/_components/(auth)/login/reset-password/success/serverComponents.tsx
  src/app/_components/(auth)/login/serverComponents.tsx
  src/app/_components/(auth)/oauth/clientComponents.tsx
  src/app/_components/(auth)/oauth/serverComponents.tsx
  src/app/_components/(auth)/register/clientComponents.tsx
  src/app/_components/(auth)/register/password/clientComponents.tsx
  src/app/_components/(auth)/register/password/serverComponents.tsx
  src/app/_components/(auth)/register/serverComponents.tsx
  src/app/_components/(auth)/register/terms/clientComponents.tsx
  src/app/_components/(auth)/register/terms/serverComponents.tsx
  src/app/_components/(auth)/register/username/clientComponents.tsx
  src/app/_components/(auth)/register/username/serverComponents.tsx
  src/app/_components/(auth)/register/verification/clientComponents.tsx
  src/app/_components/(auth)/register/verification/serverComponents.tsx
  src/app/_components/(main)/home/clientComponents.tsx
  src/app/_components/(main)/home/serverComponents.tsx
  src/app/_components/artist/artistInfo.tsx
  src/app/_hooks/useIsLogin.tsx
  src/components/artist/artistInfo.tsx
  src/components/home/library.tsx
  src/components/home/navProfileButtons.tsx
  src/components/home/navRegisterButtons.tsx
  src/components/home/navigation.tsx
  src/components/home/searchBar.tsx
  src/stories/(auth)/login/clientComponents.stories.tsx
  src/stories/(auth)/login/reset-password/clientComponents.stories.tsx
  src/stories/(auth)/login/reset-password/email/clientComponents.stories.tsx
  src/stories/(auth)/login/reset-password/success/serverComponents.stories.tsx
  src/stories/(auth)/login/serverComponents.stories.tsx
  src/stories/(auth)/register/clientComponents.stories.tsx
  src/stories/(auth)/register/password/clientComponents.stories.tsx
  src/stories/(auth)/register/password/serverComponents.stories.tsx
  src/stories/(auth)/register/serverComponents.stories.tsx
  src/stories/(auth)/register/terms/clientComponents.stories.tsx
  src/stories/(auth)/register/terms/serverComponents.stories.tsx
  src/stories/(auth)/register/username/clientComponents.stories.tsx
  src/stories/(auth)/register/username/serverComponents.stories.tsx
  src/stories/(auth)/register/verification/clientComponents.stories.tsx
  tsconfig.json
Labels: feat, refactor

#40 Feat: Search Genre Recommend Page(w/o searchParameter page)
  package-lock.json
  package.json
  public/images/chart.svg
  public/images/event.svg
  public/images/focus.svg
  public/images/jazz.svg
  public/images/k-pop.svg
  public/images/korean-music.svg
  public/images/latest-song.svg
  public/images/pop.svg
  public/images/rnb.svg
  public/images/searchButton.svg
  public/images/summer.svg
  src/app/(main)/home/api/router.tsx
  src/app/(main)/home/page.tsx
  src/app/(main)/home/search/[keyword]/page.tsx
  src/app/(main)/home/search/page.tsx
  src/app/_components/(main)/home/clientComponents.tsx
  src/app/_components/(main)/home/search/[keyword]/clientComponents.tsx
  src/app/_components/(main)/home/search/[keyword]/serverComponents.tsx
  src/app/_components/(main)/home/search/clientComponents.tsx
  src/app/_components/(main)/home/search/serverComponents.tsx
  src/app/_components/(main)/home/serverComponents.tsx
  src/app/_hooks/useSearch.tsx
  src/app/globals.css
  tailwind.config.ts
Labels: feat, fix

#43 Dev To Main Build
  src/app/(main)/home/search/[keyword]/page.tsx
  src/app/_components/(main)/home/search/serverComponents.tsx
Labels: build

#44 Dev to Main Production
  src/app/(main)/home/search/[keyword]/page.tsx
  src/app/_components/(main)/home/search/serverComponents.tsx
Labels: build

#45 Fix: Resolved name case
  src/app/(main)/home/search/[keyword]/page.tsx
  src/app/_components/(main)/home/clientComponents.tsx
  src/app/_components/(main)/home/search/[keyword]/clientComponents.tsx
Labels: build

#46 Build: Vercel build test CI
  .github/workflows/buildTest.yml
Labels: build
